version: "3.7"

networks:
  default:
    external:
      name: nat

services:
  oliver:
    container_name: oliver
    image: dockerhub.northeurope.cloudapp.azure.com/oliver:latest
    build:
      context: ..
      dockerfile: ./src/Oliver.Api/Dockerfile
    ports:
      - "8080:5000"
      - "443:5001"
    restart: always
    volumes:
      - .:C:\settings
      - ~/.aspnet/https/:C:\https
    environment:
      ASPNETCORE_URLS: https://+:5001;http://+:5000
      ASPNETCORE_Kestrel__Certificates__Default__Password: somePassword
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_HTTPS_PORT: 5001
      SETTINGS_FOLDER: /settings
